weighted = true
rmove_only = true

day_filename = "day.csv"
hh_filename = "hh.csv"
location_filename = "location.csv"
person_filename = "person.csv"
trip_filename = "trip.csv"
vehicle_filename = "vehicle.csv"

[model]
agency_model = "MTC_TM1"

[raw]
dir = "X:/survey_repos/ProjRoot_Mon-Thu20251011/WgtRoot_Mon-Thu20251011/output/full_weighted_dataset"

[00-preprocess]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/00-preprocess"
primary_respondent_only = true

[01-taz_spatial_join]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/01-taz_spatial_join"
maz_filepath = "X:/travel-model-one-master/utilities/geographies/bayarea_rtaz1454_rev1_WGS84.shp"

[02a-reformat]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/02a-reformat"

[02b-link_trips_week]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/02b-link_trips_week"
accegr_filename = "accegr_week.csv"  # access/egress
trip_linked_detail_week_filename = "trip-detail.csv"

[03a-tour_extract_week]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/03a-tour_extract_week"
personday_filename = "personday.csv"
tour_filename = "tour.csv"

[03b-assign_day]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/03b-assign_day"
weight_dir = "wt-wkday_4day"  # not currently used in step 3b, only for step 4a/4c

[04a-merge_skims]  # only implemented for step 04c for now
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/04a-merge_skims"

[04b-summary_notebooks]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/04b-summary_notebooks"
county_filepath = "Q:/GIS/Model/TAZ/SFCTA_TAZ/TAZ2454_clean.csv"
sup_dist_filepath = "Q:/GIS/Model/TAZ/SFCTA_TAZ/TAZ_SUPDIST/sftaz_wSupDist_Manual.csv"

[04c-csv_to_dat]
dir = "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Processed/TripLinking_20251012/04c-csv_to_dat"
